//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agent_order()
        {
            this.agent_order_detail = new HashSet<agent_order_detail>();
        }
    
        public int id { get; set; }
        public int agent_id { get; set; }
        public System.DateTime order_date { get; set; }
        public Nullable<int> total { get; set; }
        public bool status_order { get; set; }
        public bool status_pay { get; set; }
        public string method_pay { get; set; }
    
        public virtual agent agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agent_order_detail> agent_order_detail { get; set; }
    }
}
